project:
  type: website

website:
  title: "repo-actions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  repo-url: https://github.com/datascijedi/website
  repo-actions: [edit, issue]
  page-footer:
    border: true
    left: "Copyright 2023 © JEDI"
    center:
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md
    right:
    - text: "License"
      href: LICENSE.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
